# Generated by Django 3.1.7 on 2021-03-11 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210311_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.JSONField(db_index=True, help_text='Value must be valid JSON'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
